In [1]:
import time

import pandas
import argparse

import chainer
from chainer import cuda, Function, report, training, utils, Variable
from chainer import datasets, iterators, optimizers, serializers
from chainer import Link, Chain, ChainList
import chainer.functions as F
import chainer.links as L
from chainer import training
from chainer.training import extensions
from chainer.datasets import tuple_dataset
from chainer.dataset import convert, concat_examples
import numpy 

import os

In [2]:
import glob

a_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/A-*"))
b_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/B-*"))
c_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/C-*"))
d_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/D-*"))
e_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/E-*"))
f_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/F-*"))
g_list = sorted(glob.glob("C:/Users/Owner/Desktop/txt/G-*"))

In [3]:
xls = pandas.read_csv(a_list[0], comment="#", delimiter="\t", header=None)
col = xls.as_matrix()[:,0]

j = 0
for list_ in (a_list, b_list, c_list, d_list, e_list, f_list, g_list):
#     print(list_)
    for i, fname in enumerate (list_):
        xls = pandas.read_csv(fname, comment="#", delimiter="\t", header=None)
        if j == 0:
            arr = xls.as_matrix()[:,1]
            hddr = os.path.split(fname)[1].split(".")[0]
        else:
            arr = numpy.vstack((arr, xls.as_matrix()[:,1]))
            hddr = numpy.hstack((hddr, os.path.split(fname)[1].split(".")[0]))
        j += 1

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  del sys.path[0]


In [4]:
print(arr.shape, col.shape, hddr.shape)

(160, 2385) (2385,) (160,)


In [5]:
df = pandas.DataFrame(data=arr.T,  # spectra, reference
                      index=col,  # wavenumber
                      columns=hddr)  # file name

In [6]:
df.to_excel("C:/Users/Owner/Desktop/CCMI_2.xlsx")

# 練習

## スタイルの設定
*Itaric* の表示

**Bold** の表示

***Itaric & Bold*** の表示

~~取り消し線~~ の表示

## 引用の設定
引用文の指定。以下、引用のテキスト

>引用のテキスト
>>さらに引用
>>>もひとつ引用

引用終わり。本文に戻る

## ソースコードの設定
デフォルトのソースコード
```
def hello():
    print("hello")
```

言語を指定した場合
```Python
def hello():
    print(hello)
```

表示の違いを確認

## 仕切りの設定
テキストその1.
***
テキストその2.

## リンクの設定
リンクの表示1. https://google.com リンクの表示

リンクの表示2. [リンク](https://google.com)の表示

引用によるリンクの設定。[Google][1]や[Yahoo!][2]のリンク。

[1]: https://google.com "Google"
[2]: https://yahoo.co.jp "Yahoo!"

# numpy と scipy

In [1]:
import numpy as np
import scipy 

### 配列の生成

In [4]:
arr = np.array([10, 20, 30.])
print(arr)

arr0 = np.zeros(5)
arr1 = np.ones(5)
print(arr0)
print(arr1)

[10. 20. 30.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


### 等差数列

In [5]:
arr_1 = np.arange(0, 100, 20)
arr_2 = np.linspace(0, 100, 5)
print(arr_1)
print(arr_2)

[ 0 20 40 60 80]
[  0.  25.  50.  75. 100.]


### ベクトル演算

In [6]:
# ベクトルと数値の計算
arr_3 = np.array([1, 2, 3, 5, 8])
print(arr_3)

print(arr_3 + 10)
print(arr_3 - 10)
print(arr_3 * 2)
print(arr_3 / 2)
print(arr_3 % 2)

[1 2 3 5 8]
[11 12 13 15 18]
[-9 -8 -7 -5 -2]
[ 2  4  6 10 16]
[0.5 1.  1.5 2.5 4. ]
[1 0 1 1 0]


In [8]:
# ベクトル同士の計算
arr_4 = np.array([1, 2, 3, 5])
arr_5 = np.array([8, 13, 21, 34])

print(arr_5 + arr_4)
print(arr_5 - arr_4)
print(arr_5 * arr_4)
print(arr_5 / arr_4)
print(arr_5 % arr_4)

[ 9 15 24 39]
[ 7 11 18 29]
[  8  26  63 170]
[8.  6.5 7.  6.8]
[0 1 0 4]


### 行列の作成

In [10]:
arr_6 = np.matrix([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 単位行列の生成
arr_7 = np.identity(3)
arr_8 = np.identity(5)

print(arr_7)
print(arr_8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# 非正方行列の作成
arr_9 = np.eye(5, 7, 0)
arr_10 = np.eye(5, 7, 2)

print(arr_9)
print(arr_10)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [14]:
# そのほかの対角行列
arr_11 = np.diag([1, 2, 3])
arr_12 = np.diag([3, 5, 8, 13, 21])

print(arr_11)
print(arr_12)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[ 3  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 21]]


In [16]:
# ベクトルから行列への変換
arr_13 = np.array([1, 2, 3, 5, 8, 13, 21, 34, 55])
arr_14 = arr_13.reshape((3,3))

print(arr_13)
print(arr_14)

[ 1  2  3  5  8 13 21 34 55]
[[ 1  2  3]
 [ 5  8 13]
 [21 34 55]]


In [17]:
# 転置
arr_15 = np.array([1, 2, 3, 5, 8, 13, 21, 34, 55])
arr_16 = arr_15.reshape((3,3))
print(arr_16)
print(arr_16.T)

[[ 1  2  3]
 [ 5  8 13]
 [21 34 55]]
[[ 1  5 21]
 [ 2  8 34]
 [ 3 13 55]]


In [19]:
# 行列からベクトル
arr_17 = np.diag([1, 2, 3, 5])
arr_18 = np.ravel(arr_17)

print(arr_17)
print(arr_18)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]
[1 0 0 0 0 2 0 0 0 0 3 0 0 0 0 5]


### ベクトル・行列の演算

In [20]:
# ベクトルの結合
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 8, 13])
arr3 = arr1 + arr2
arr4 = np.ravel([arr1, arr2])
print(arr3)
print(arr4)

[ 6 10 16]
[ 1  2  3  5  8 13]


## pandas

In [9]:
import pandas as pd

### DataFrame

In [29]:
arr1 = ['山田'] * 5 + ['田中'] * 5 + ['佐藤'] * 5 + ['鈴木'] * 5 + ['高橋'] * 5 \
 + ['武田'] * 5 + ['中西'] * 5 +  ['江口'] * 5  + ['高野'] * 5 +  ['小川'] * 5 

arr2 = ['国語','算数','英語','理科','社会'] * 10

arr3 = [np.random.randint(0,100) for i in range(50)]

print(arr1)
print(arr2)
print(arr3)

['山田', '山田', '山田', '山田', '山田', '田中', '田中', '田中', '田中', '田中', '佐藤', '佐藤', '佐藤', '佐藤', '佐藤', '鈴木', '鈴木', '鈴木', '鈴木', '鈴木', '高橋', '高橋', '高橋', '高橋', '高橋', '武田', '武田', '武田', '武田', '武田', '中西', '中西', '中西', '中西', '中西', '江口', '江口', '江口', '江口', '江口', '高野', '高野', '高野', '高野', '高野', '小川', '小川', '小川', '小川', '小川']
['国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会', '国語', '算数', '英語', '理科', '社会']
[86, 99, 44, 91, 78, 18, 5, 29, 55, 4, 39, 23, 38, 41, 58, 59, 1, 60, 78, 40, 2, 97, 58, 63, 64, 69, 56, 80, 47, 38, 5, 64, 86, 37, 82, 64, 44, 8, 57, 68, 75, 39, 17, 93, 76, 58, 74, 15, 77, 85]


In [30]:
data = list(zip(arr1,arr2,arr3))
df = pd.DataFrame(data=data, columns=['名前','教科','点数'])
df.info()
print()
df[:5]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
名前    50 non-null object
教科    50 non-null object
点数    50 non-null int64
dtypes: int64(1), object(2)
memory usage: 1.2+ KB



名前  教科  点数
0  山田  国語  86
1  山田  算数  99
2  山田  英語  44
3  山田  理科  91
4  山田  社会  78

In [31]:
df['点数'][:10]

0    86
1    99
2    44
3    91
4    78
5    18
6     5
7    29
8    55
9     4
Name: 点数, dtype: int64

In [32]:
# 列の追加
df['総合'] = [np.random.randint(0,100) for i in range(50)]
df[:5]

名前  教科  点数  総合
0  山田  国語  86  18
1  山田  算数  99  73
2  山田  英語  44   0
3  山田  理科  91  31
4  山田  社会  78  24

In [20]:
del df['総合']

In [33]:
# 列名の変更
df.columns = ['氏名', '教科', '中間', '期末']
df[:5]

氏名  教科  中間  期末
0  山田  国語  86  18
1  山田  算数  99  73
2  山田  英語  44   0
3  山田  理科  91  31
4  山田  社会  78  24

In [34]:
# 行の追加
new_data = [('上杉','国語', 95, 89),
            ('上杉','算数', 87, 71),
            ('上杉','英語', 69, 93),
            ('上杉','理科', 73, 52),
            ('上杉','社会', 54, 60)]

new_df = pd.DataFrame(data=new_data, columns=['氏名', '教科', '中間', '期末'])
df2 = df.append(new_df, ignore_index=True)
df2[45:]

氏名  教科  中間  期末
45  小川  国語  58  80
46  小川  算数  74  26
47  小川  英語  15  98
48  小川  理科  77  30
49  小川  社会  85  69
50  上杉  国語  95  89
51  上杉  算数  87  71
52  上杉  英語  69  93
53  上杉  理科  73  52
54  上杉  社会  54  60

In [35]:
(rows, cols) = df2.shape
df2.loc[rows] = ['黒田', '国語', 15, 20]
df2.loc[rows+1] = ['黒田', '算数', 15, 20]
df2.loc[rows+2] = ['黒田', '英語', 15, 20]
df2.loc[rows+3] = ['黒田', '理科', 15, 20]
df2.loc[rows+4] = ['黒田', '社会', 15, 20]
df2.tail(10)

氏名  教科  中間  期末
50  上杉  国語  95  89
51  上杉  算数  87  71
52  上杉  英語  69  93
53  上杉  理科  73  52
54  上杉  社会  54  60
55  黒田  国語  15  20
56  黒田  算数  15  20
57  黒田  英語  15  20
58  黒田  理科  15  20
59  黒田  社会  15  20

In [36]:
# インデックスの変更
df2.index = list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ12345678')
df2.head(10)

氏名  教科  中間  期末
a  山田  国語  86  18
b  山田  算数  99  73
c  山田  英語  44   0
d  山田  理科  91  31
e  山田  社会  78  24
f  田中  国語  18  37
g  田中  算数   5  16
h  田中  英語  29  13
i  田中  理科  55  58
j  田中  社会   4  64

In [40]:
# csvファイルの読み込み
csv_df = pd.read_csv("C:/Users/Owner/Desktop/[190611]kurasawa/Blood_glucose_level/1.csv", header=None, names=['A', 'B', 'C'])
csv_df[:5]

A         B         C
0  1823.5881 -0.379559 -0.398127
1  1823.5882 -0.436725 -0.215821
2  1823.5883 -0.013988  0.038587
3  1823.5884  0.073285 -0.481058
4  1823.5885 -0.100122 -0.124777